idf_component_register(
    SRCS
        "app_main.c"
        "app_cfg.c"
        "wifi_mgr.c"
        "serial_port.c"
        "bridge.c"
        "net_srv.c"
        "web_server.c"
        "mqtt_bridge.c"
        "wol.c"
        "log_ring.c"
    INCLUDE_DIRS "."
    REQUIRES
        esp_wifi
        esp_netif
        nvs_flash
        esp_http_server
        esp_event
        esp_timer
        mdns
        mqtt
        json
        driver
        lwip
        vfs
        app_update
        esp_partition
)
